# Generated by Django 3.1.2 on 2021-03-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210307_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thematic_sections',
            field=models.ManyToManyField(through='articles.ArticleThematics', to='articles.Thematics'),
        ),
        migrations.AlterField(
            model_name='articlethematics',
            name='Thematics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematics', to='articles.thematics'),
        ),
    ]
