# Generated by Django 3.1.2 on 2021-03-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210307_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethematics',
            name='Article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articlethematics',
            name='Thematics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.thematics'),
        ),
    ]
