# Generated by Django 3.1.2 on 2021-03-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210307_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethematics',
            name='Thematics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.thematics'),
        ),
    ]
