# Generated by Django 3.1.2 on 2021-03-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210308_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethematics',
            name='Thematics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematic', to='articles.thematics'),
        ),
    ]
